### PR TITLE
Add optional basic auth support for CSR

### LINKED ISSUE #33: Add HTTP Basic Auth
This is needed for the [Confluent Cloud](https://docs.confluent.io/current/security/basic-auth.html)

### PR DESCRIPTION
**Pull request by Strech**
Closes #33 

## TODO

- [x] Add config options
- [x] Update registry storage
- [x] Update http client
- [x] Add tests
- [x] Update docs

### CODE REVIEW

**Comment by Strech** [comment]
@alex88 May I ask you to test this? I change a bit configuration to be less dependent on order and by more like simple tuple

```elixir
config :avrora,
  registry_url: "...",
  registy_auth: {:basic, ["username", "password"]}
```

**Comment by alex88** [comment]
Thanks for the quick update! I've just deployed our app with this branch end everything is working properly!

**Comment by Strech** [comment]
@alex88 I'm planning to do few performance optimization. I want to move some dynamic parts to compile-time if it will be possible to keep code testable. I will ping you one more time then once it will be ready-to merge

**Comment by alex88** [comment]
@Strech sure, thanks for working on this!

**Comment by Strech** [comment]
@alex88 I've tried different approaches and them either reduce testing or development comfort. So I will leave it as-is for now and release today/tomorrow 🚀

**Comment by alex88** [comment]
@Strech awesome! Thank you for this!

**Pull request merged**
