### PR TITLE
Make the custom Client configurable

### LINKED ISSUE #90: Any way to configure the registry_url at startup?
We are currently using 
```
  use Avrora.Client,
    registry_url: Application.get_env(:the_app, TheApp.AvroClient)[:url],
    schemas_path: Application.get_env(:the_app,  TheApp.AvroClient)[:schemas_path]
```
to define our own client module.
But as you already know, those configurations must come from compile time environment. 
Is there any way to configure it at runtime, when the application starts?
Tried looking at the supervisor tree, but didn't find anything.

Thank you in advance for your answer, and thank you for your awesome library!

### PR DESCRIPTION
**Pull request by juanperi**
Closes #90 

I've taken a stab at adding runtime configuration to custom Clients.
I've not added any docs yet, as i'm not sure if you will like my approach or not.

### CODE REVIEW

**Comment by Strech** [comment]
Hey @juanperi thanks for your contribution. Yes the general idea is exactly like you have proposed 👍🏼 

Unfortunately, implementation is sub-optimal due to several things:

1. A new public method in the wrong spot (Client should know nothing about Config implementations)
2. Module is passed to the options, but it's known in compilation time as `module` variable
3. The `get_config` method is hard to understand, which config goes first, module or macros?
4. A minor thing, but I'm not a big fan of programming in tests. It's hard to read, hard to understand, and easy to make a mistake. I would rather have fewer tests, but good ones.

I'm about to implement and release it this week, just in case.

**Comment by juanperi** [comment]
hey, I've updated the code with your suggestions 1-3, but feel free to close this PR to follow your approach
I've done it because i'll be using the fork I've created until you release the new version. 

Thank you for your review anyways!

**Comment by juanperi** [comment]
BTW, I just realized that If I use otp_app to be able to configure the client at runtime, I cannot use schemas_path anymore to set the fixtures for tests in the tests namespace, as the existance of OTP app converts the schemas path relative to the app folder. Which would mean that my test fixtures must live in the priv folder, and they will end up in the release.

**Comment by juanperi** [comment]
I've added a new commit, just to expose my problem with the schemas_path.
I do understand that changing the meaning of the field (expanding vs not expanding) would be a breaking change though

**Comment by Strech** [comment]
Hey @juanperi a heads up. I've prepared PR #92 with some compile-time optimizations for runtime configuration. I'm planning to release it in a few hours today 👏

**Comment by Strech** [comment]
I would like to say thank you for your support, effort, and healthy conversation around this enhancement. I've released [v0.23.0](https://github.com/Strech/avrora/releases/tag/v0.23.0) with all improvements 🍾

**Pull request closed without merging**
